dubbo:
  application:
    name: dubbo3Consumer
  registry:
    address: zookeeper://127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
server:
  port: 8090
