spring:
  application:
    name: dubbo3provider

dubbo:
  application:
    name: dubbo3provider
  registry:
    address: zookeeper://127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  config-center:
    address: zookeeper://127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
  protocol:
    name: dubbo
    port: 20890
  metadata-report:
    address: zookeeper://127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183

