spring:
  application:
    name: wechat
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    mongodb:
      uri: mongodb://127.0.0.1/wechat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat
    username: root
    password: 123456
wework:
  corpid: XXXXxxxxx
  secret: xxxxxxxxxx
  private-key: xxxxxxxxxxxxxxx